first commit
volgraud/go_final_project pull request #1
Opened 2024-08-02 14:38 UTC by volgraud

2024-08-03 11:14 UTC, dirtymew requested changes
Привет Владимир

отличная работа
 - документация
 - логирование
 - хорошая архитектура и разделение на компоненты (посмотри еще https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10) 
 - структура проекта (посмотри еще на https://github.com/golang-standards/project-layout  )


Дал комментарии что поправить и улучшить 

Остальные задания со звездочкой доделывать будешь?

2024-08-03 11:14 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o todo_app
CGO_ENABLED=0 GOOS=linux GOARCH=amd64  это лучше в ENV или .env

2024-08-03 11:14 UTC, dirtymew commented on .gitignore
> +.env
лучше наоборот его добавить в репозиторий

2024-08-03 11:14 UTC, dirtymew commented on config/config.go
> +	} else {
лучше без else стараться обходиться - так код чище и читабельнее

2024-08-03 11:14 UTC, dirtymew commented on storage/task.go
> +func (s *Storage) GetList() ([]task.Task, error) {
мб просто List(filter strung) - так интерфейс storage будет попроще

2024-08-03 11:14 UTC, dirtymew commented on storage/task.go
> +		`SELECT *
лучше явно поля указывать чем *

2024-08-03 11:14 UTC, dirtymew commented on storage/task.go
> +		log.Println("can't get tasks by GetList:", rows.Err())
мб логировать на уровень выше ошибки...

2024-08-03 11:14 UTC, dirtymew commented on storage/task.go
> +	log.Printf("looking for tasks with search parameter %s", search)
не очень хорошо на каждый запрос лог писать - только на ошибки

или использовать продвинутый логгер с разными уровнями логгирования - но это сильно за рамками курса

2024-08-03 11:14 UTC, dirtymew commented on storage/task.go
> +		target := date.Format("20060102")
20060102 - лучше глобальную константу сделать и везде ее использовать

2024-08-03 11:14 UTC, dirtymew commented on storage/task.go
> +
if rows.Err() != nil  - забыл

2024-08-03 11:14 UTC, dirtymew commented on storage/task.go
> +
тут и в delete можно проверить RowsAffected и вернуть ошибку если ничего не поменялось

2024-08-03 11:14 UTC, dirtymew commented on task/check.go
> +		t.Date = time.Now().Format("20060102")
есть константы - используй ее

2024-08-03 11:14 UTC, dirtymew commented on server/server.go
> +	log.Printf("Starting server on port %s", s.httpServer.Addr)
супер что добавил логирование

2024-08-03 11:14 UTC, dirtymew commented on main.go
> +	log.Println("Server stopped")
сюда никогда ни дойдет выполнение

2024-08-03 11:14 UTC, dirtymew commented on main.go
> +
не нашел где подлючение к бд закрывается после завершения работы приложения

2024-08-03 11:14 UTC, dirtymew commented on server/handler/task.go
> +			log.Fatalf("can't write response: %v", err)
тут не очень хорошо - падать в панику на запросы - не делай log.Fatalf в хендлерах

2024-08-03 17:44 UTC, volgraud commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o todo_app
Пока что задания со звездочкой доделывать не буду, думаю не успею, но для портфолио доделаю аутентификацию и правила для недель и месяцев.

2024-08-03 17:45 UTC, volgraud commented on main.go
> +
добавил в storage.go функцию Close, закрывать соединение с бд

2024-08-04 08:08 UTC, dirtymew approved these changes
Привет Владимир

задание выполнено 

Поздравляю и желаю удачи

ЗЫ Если будешь из него готовить портфолио:
 - переработай логирование - например сделай middleware для хендлеров и логируй там, если хочешь логировать все то возьми логер по типу zap или logrus и сделай режим работы в режиме debug
 - стоит ввести уровнь абстракции service - посмотри внимательно на задание с посылками там есть пример
 - стоит абсрагировать компоненты интерфейсами - типа storage и server и service

2024-08-04 08:08 UTC, dirtymew commented on server/handler/getnextdate.go
> +	now, err := time.Parse("20060102", r.FormValue("now"))
тут тоже константу использовать стоит

2024-08-04 08:08 UTC, dirtymew commented on server/handler/getnextdate.go
> +	log.Println("Received reqest GetNextDate")
лучше логировать только ошибки - так много мусора в логах будет 

или использовать продвинутые логгеры с разным уровнем логирования

2024-08-04 08:08 UTC, dirtymew commented on server/handler/task.go
> +		} else {
старайся не использовать else там где можно и без него )

2024-08-05 05:24 UTC, merged